#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage:
  setup-pipeline.sh plan       --config <env-file>
  setup-pipeline.sh apply-aws  --config <env-file>
  setup-pipeline.sh apply-azure --config <env-file>
  setup-pipeline.sh apply-all  --config <env-file>
  setup-pipeline.sh upload-secure-files --config <env-file>
  setup-pipeline.sh preflight  --config <env-file>
  setup-pipeline.sh verify     --config <env-file>

The default is a read-only plan. External changes require an explicit apply
mode. The AWS apply requires AWS_PERMISSIONS_POLICY_FILE to point to a reviewed
IAM permissions policy; no broad policy is generated by this script.
USAGE
  exit 2
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

need_command() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

mode="plan"
config_file=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    plan|apply-aws|apply-azure|apply-all|upload-secure-files|preflight|verify)
      mode="$1"
      shift
      ;;
    --config)
      [[ $# -ge 2 ]] || usage
      config_file="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      usage
      ;;
  esac
done

[[ -n "$config_file" ]] || usage
[[ -f "$config_file" ]] || die "Config file not found: $config_file"

# The config is a local, user-owned file. It contains identifiers only; never
# put AWS keys, PATs, client secrets, or secure-file contents in it.
# shellcheck disable=SC1090
source "$config_file"

AZDO_ORGANIZATION_URL="${AZDO_ORGANIZATION_URL%/}"

: "${AZDO_ORGANIZATION_URL:?AZDO_ORGANIZATION_URL is required}"
: "${AZDO_ORGANIZATION_NAME:?AZDO_ORGANIZATION_NAME is required}"
: "${AZDO_ORGANIZATION_GUID:?AZDO_ORGANIZATION_GUID is required}"
: "${AZDO_PROJECT:?AZDO_PROJECT is required}"
: "${AZDO_PIPELINE_NAME:?AZDO_PIPELINE_NAME is required}"
: "${AZDO_SERVICE_CONNECTION_NAME:?AZDO_SERVICE_CONNECTION_NAME is required}"
: "${AZDO_REPOSITORY_TYPE:?AZDO_REPOSITORY_TYPE is required}"
: "${AZDO_REPOSITORY:?AZDO_REPOSITORY is required}"
: "${AZDO_BRANCH:?AZDO_BRANCH is required}"
: "${AZDO_PIPELINE_YAML:?AZDO_PIPELINE_YAML is required}"
: "${AWS_REGION:?AWS_REGION is required}"
: "${AWS_MANAGEMENT_ACCOUNT_ID:?AWS_MANAGEMENT_ACCOUNT_ID is required}"
: "${AWS_DEPLOYMENT_ROLE_NAME:?AWS_DEPLOYMENT_ROLE_NAME is required}"
: "${AWS_PERMISSIONS_POLICY_NAME:?AWS_PERMISSIONS_POLICY_NAME is required}"
: "${BOOTSTRAP_OUTPUT_DIR:=.azuredevops-bootstrap}"

[[ "$AZDO_REPOSITORY_TYPE" == "github" || "$AZDO_REPOSITORY_TYPE" == "tfsgit" ]] \
  || die "AZDO_REPOSITORY_TYPE must be github or tfsgit"
[[ "$AZDO_ORGANIZATION_GUID" =~ ^[0-9a-fA-F-]{36}$ ]] \
  || die "AZDO_ORGANIZATION_GUID must be a GUID"
[[ "$AWS_MANAGEMENT_ACCOUNT_ID" =~ ^[0-9]{12}$ ]] \
  || die "AWS_MANAGEMENT_ACCOUNT_ID must be a 12-digit account ID"

script_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repository_root="$(cd "$script_root/../.." && pwd)"
output_dir="$repository_root/$BOOTSTRAP_OUTPUT_DIR"
mkdir -p "$output_dir"

oidc_url="https://vstoken.dev.azure.com/$AZDO_ORGANIZATION_GUID"
oidc_host="vstoken.dev.azure.com/$AZDO_ORGANIZATION_GUID"
oidc_provider_arn="arn:aws:iam::$AWS_MANAGEMENT_ACCOUNT_ID:oidc-provider/$oidc_host"
role_arn="arn:aws:iam::$AWS_MANAGEMENT_ACCOUNT_ID:role/$AWS_DEPLOYMENT_ROLE_NAME"
service_connection_subject="sc://$AZDO_ORGANIZATION_NAME/$AZDO_PROJECT/$AZDO_SERVICE_CONNECTION_NAME"

require_jq() {
  need_command jq
}

assert_apply_configuration() {
  [[ "$AZDO_ORGANIZATION_URL" != *replace-me* ]] \
    || die "Replace the AZDO_ORGANIZATION_URL placeholder before applying"
  [[ "$AZDO_ORGANIZATION_NAME" != "replace-me" && "$AZDO_PROJECT" != "replace-me" ]] \
    || die "Replace the Azure DevOps organization and project placeholders before applying"
  [[ "$AZDO_ORGANIZATION_GUID" != "00000000-0000-0000-0000-000000000000" ]] \
    || die "Replace the Azure DevOps organization GUID placeholder before applying"
  [[ "$AWS_MANAGEMENT_ACCOUNT_ID" != "000000000000" ]] \
    || die "Replace the AWS account placeholder before applying"
  [[ "$AZDO_REPOSITORY" != *replace-me* ]] \
    || die "Replace the repository placeholder before applying"
}

write_manifests() {
  require_jq

  jq -n \
    --arg host "$oidc_host" \
    --arg provider "$oidc_provider_arn" \
    --arg subject "$service_connection_subject" \
    '{Version:"2012-10-17",Statement:[{Sid:"AzureDevOpsOidc",Effect:"Allow",Principal:{Federated:$provider},Action:"sts:AssumeRoleWithWebIdentity",Condition:{StringEquals:{($host+":aud"):"api://AzureADTokenExchange",($host+":sub"):$subject}}}]}' \
    > "$output_dir/aws-oidc-role-trust.json"

  jq -n \
    --arg url "$oidc_url" \
    --argjson tags '[{"Key":"ManagedBy","Value":"AzureDevOpsBootstrap"},{"Key":"Purpose","Value":"TerraformDeployment"}]' \
    '{Url:$url,ClientIDList:["api://AzureADTokenExchange"],Tags:$tags}' \
    > "$output_dir/aws-oidc-provider-request.json"

  jq -n \
    --arg name "$AZDO_SERVICE_CONNECTION_NAME" \
    --arg role "$role_arn" \
    --arg project "$AZDO_PROJECT" \
    --arg project_id "${AZDO_PROJECT_ID:-}" \
    '{data:{},name:$name,type:"AWS",url:"https://aws.amazon.com/",authorization:{parameters:{assumeRoleArn:$role,useOIDC:"true"},scheme:"UsernamePassword"},isShared:false,isReady:true,serviceEndpointProjectReferences:[{projectReference:{id:$project_id,name:$project},name:$name}]}' \
    > "$output_dir/aws-service-connection.json"

  cat > "$output_dir/replication-checklist.txt" <<CHECKLIST
Azure DevOps Terraform bootstrap

OIDC issuer: $oidc_url
OIDC provider ARN: $oidc_provider_arn
AWS role ARN: $role_arn
Service connection subject: $service_connection_subject

Required Azure DevOps secure files:
  aws-terraform-01-organization.backend.hcl
  aws-terraform-01-organization.tfvars
  aws-terraform-02-governance.backend.hcl
  aws-terraform-02-governance.tfvars
  aws-terraform-03-production.backend.hcl
  aws-terraform-03-production.tfvars

Required environments:
  aws-organization
  aws-governance
  aws-production

Required environment checks:
  branch control: refs/heads/main
  manual approval: configured by environment owner
  exclusive lock: enabled where concurrent applies are not allowed

The AWS permissions policy is intentionally not generated. Review the stage
resources and provide a policy file to AWS_PERMISSIONS_POLICY_FILE before
running apply-aws.
CHECKLIST
}

resolve_project_id() {
  if [[ -n "${AZDO_PROJECT_ID:-}" && "$AZDO_PROJECT_ID" != "00000000-0000-0000-0000-000000000000" ]]; then
    printf '%s\n' "$AZDO_PROJECT_ID"
    return
  fi

  need_command az
  az devops project show \
    --organization "$AZDO_ORGANIZATION_URL" \
    --project "$AZDO_PROJECT" \
    --query id -o tsv
}

apply_aws() {
  need_command aws
  require_jq
  assert_apply_configuration
  [[ -n "${AWS_PROFILE:-}" ]] || die "AWS_PROFILE must be set for apply-aws"
  [[ -f "${AWS_PERMISSIONS_POLICY_FILE:-}" ]] \
    || die "AWS_PERMISSIONS_POLICY_FILE must point to a reviewed policy file"
  jq empty "$AWS_PERMISSIONS_POLICY_FILE" \
    || die "AWS_PERMISSIONS_POLICY_FILE is not valid JSON"
  ! grep -q 'REPLACE_' "$AWS_PERMISSIONS_POLICY_FILE" \
    || die "AWS_PERMISSIONS_POLICY_FILE still contains a REPLACE_ placeholder"

  local caller_account provider_arn existing_url existing_client_ids role_exists
  caller_account="$(aws --profile "$AWS_PROFILE" --region "$AWS_REGION" sts get-caller-identity --query Account --output text)"
  [[ "$caller_account" == "$AWS_MANAGEMENT_ACCOUNT_ID" ]] \
    || die "AWS profile targets account $caller_account, expected $AWS_MANAGEMENT_ACCOUNT_ID"

  provider_arn=""
  existing_client_ids=""
  while IFS= read -r candidate; do
    existing_url="$(aws --profile "$AWS_PROFILE" --region "$AWS_REGION" iam get-open-id-connect-provider --open-id-connect-provider-arn "$candidate" --query Url --output text 2>/dev/null || true)"
    if [[ "$existing_url" == "$oidc_url" ]]; then
      provider_arn="$candidate"
      existing_client_ids="$(aws --profile "$AWS_PROFILE" --region "$AWS_REGION" iam get-open-id-connect-provider --open-id-connect-provider-arn "$candidate" --query 'ClientIDList' --output json)"
      break
    fi
  done < <(aws --profile "$AWS_PROFILE" --region "$AWS_REGION" iam list-open-id-connect-providers --query 'OpenIDConnectProviderList[].Arn' --output text | tr '\t' '\n')

  if [[ -z "$provider_arn" ]]; then
    aws --profile "$AWS_PROFILE" --region "$AWS_REGION" iam create-open-id-connect-provider \
      --cli-input-json "file://$output_dir/aws-oidc-provider-request.json" >/dev/null
    provider_arn="$oidc_provider_arn"
  elif ! jq -e 'index("api://AzureADTokenExchange")' <<<"$existing_client_ids" >/dev/null; then
    aws --profile "$AWS_PROFILE" --region "$AWS_REGION" iam add-client-id-to-open-id-connect-provider \
      --open-id-connect-provider-arn "$provider_arn" \
      --client-id "api://AzureADTokenExchange"
  fi

  role_exists="$(aws --profile "$AWS_PROFILE" --region "$AWS_REGION" iam get-role --role-name "$AWS_DEPLOYMENT_ROLE_NAME" --query 'Role.RoleName' --output text 2>/dev/null || true)"
  if [[ -z "$role_exists" || "$role_exists" == "None" ]]; then
    aws --profile "$AWS_PROFILE" --region "$AWS_REGION" iam create-role \
      --role-name "$AWS_DEPLOYMENT_ROLE_NAME" \
      --assume-role-policy-document "file://$output_dir/aws-oidc-role-trust.json" \
      --description "Azure DevOps OIDC role for staged AWS Terraform" >/dev/null
  else
    aws --profile "$AWS_PROFILE" --region "$AWS_REGION" iam update-assume-role-policy \
      --role-name "$AWS_DEPLOYMENT_ROLE_NAME" \
      --policy-document "file://$output_dir/aws-oidc-role-trust.json"
  fi

  aws --profile "$AWS_PROFILE" --region "$AWS_REGION" iam put-role-policy \
    --role-name "$AWS_DEPLOYMENT_ROLE_NAME" \
    --policy-name "$AWS_PERMISSIONS_POLICY_NAME" \
    --policy-document "file://$AWS_PERMISSIONS_POLICY_FILE"

  echo "AWS OIDC provider and deployment role are configured for $caller_account."
}

apply_azure() {
  need_command az
  require_jq
  assert_apply_configuration

  local project_id endpoint_id pipeline_args
  project_id="$(resolve_project_id)"
  [[ "$project_id" =~ ^[0-9a-fA-F-]{36}$ ]] || die "Could not resolve an Azure DevOps project GUID"

  create_environment_if_missing() {
    local environment_name="$1"
    local environment_list environment_id environment_body
    environment_list="$(az devops invoke \
      --organization "$AZDO_ORGANIZATION_URL" \
      --area distributedtask \
      --resource environments \
      --route-parameters "project=$project_id" \
      --http-method GET \
      --api-version 7.1-preview.1)"
    environment_id="$(jq -r --arg name "$environment_name" '.value[]? | select(.name == $name) | .id' <<<"$environment_list" | head -n 1)"
    if [[ -n "$environment_id" && "$environment_id" != "null" ]]; then
      echo "Environment already exists: $environment_name"
      return
    fi
    environment_body="$output_dir/environment-$environment_name.json"
    jq -n --arg name "$environment_name" \
      '{name:$name,description:"Protected Terraform deployment environment"}' \
      > "$environment_body"
    az devops invoke \
      --organization "$AZDO_ORGANIZATION_URL" \
      --area distributedtask \
      --resource environments \
      --route-parameters "project=$project_id" \
      --http-method POST \
      --api-version 7.1-preview.1 \
      --in-file "$environment_body" >/dev/null
    echo "Created environment: $environment_name"
  }

  jq --arg project_id "$project_id" \
    '.serviceEndpointProjectReferences[0].projectReference.id = $project_id' \
    "$output_dir/aws-service-connection.json" > "$output_dir/aws-service-connection.resolved.json"

  endpoint_id="$(az devops service-endpoint list \
    --organization "$AZDO_ORGANIZATION_URL" \
    --project "$project_id" \
    --query "[?name=='$AZDO_SERVICE_CONNECTION_NAME'].id | [0]" -o tsv)"

  if [[ -z "$endpoint_id" || "$endpoint_id" == "None" ]]; then
    az devops service-endpoint create \
      --organization "$AZDO_ORGANIZATION_URL" \
      --project "$project_id" \
      --service-endpoint-configuration "$output_dir/aws-service-connection.resolved.json" >/dev/null
    endpoint_id="$(az devops service-endpoint list --organization "$AZDO_ORGANIZATION_URL" --project "$project_id" --query "[?name=='$AZDO_SERVICE_CONNECTION_NAME'].id | [0]" -o tsv)"
  else
    echo "AWS service connection already exists: $endpoint_id"
  fi

  local endpoint_check endpoint_type endpoint_role endpoint_oidc
  [[ -n "$endpoint_id" && "$endpoint_id" != "None" ]] \
    || die "Could not resolve the AWS service connection after creation"
  endpoint_check="$(az devops service-endpoint show \
    --organization "$AZDO_ORGANIZATION_URL" \
    --project "$project_id" \
    --id "$endpoint_id" \
    --query '{type:type,role:authorization.parameters.assumeRoleArn,useOIDC:authorization.parameters.useOIDC}' \
    -o json)"
  endpoint_type="$(jq -r '.type // empty' <<<"$endpoint_check")"
  endpoint_role="$(jq -r '.role // empty' <<<"$endpoint_check")"
  endpoint_oidc="$(jq -r '.useOIDC // empty' <<<"$endpoint_check")"
  [[ "$endpoint_type" == "AWS" ]] || die "Existing AWS service connection has unexpected type: $endpoint_type"
  [[ "$endpoint_role" == "$role_arn" ]] || die "AWS service connection points to an unexpected role; review it before continuing"
  [[ "$endpoint_oidc" == "true" ]] || die "AWS service connection is not configured for OIDC; review it before continuing"

  pipeline_args=(
    --name "$AZDO_PIPELINE_NAME"
    --organization "$AZDO_ORGANIZATION_URL"
    --project "$project_id"
    --repository "$AZDO_REPOSITORY"
    --repository-type "$AZDO_REPOSITORY_TYPE"
    --branch "$AZDO_BRANCH"
    --yml-path "$AZDO_PIPELINE_YAML"
    --skip-first-run true
  )
  if [[ -n "${AZDO_REPOSITORY_SERVICE_CONNECTION:-}" ]]; then
    pipeline_args+=(--service-connection "$AZDO_REPOSITORY_SERVICE_CONNECTION")
  fi

  if az pipelines show --name "$AZDO_PIPELINE_NAME" --organization "$AZDO_ORGANIZATION_URL" --project "$project_id" >/dev/null 2>&1; then
    echo "Pipeline already exists: $AZDO_PIPELINE_NAME"
  else
    az pipelines create "${pipeline_args[@]}" >/dev/null
    echo "Created Azure DevOps pipeline: $AZDO_PIPELINE_NAME"
  fi

  create_environment_if_missing aws-organization
  create_environment_if_missing aws-governance
  create_environment_if_missing aws-production
  echo "Configure environment approvals, branch control, and locks from $output_dir/replication-checklist.txt."
  echo "AWS service connection: $AZDO_SERVICE_CONNECTION_NAME ($endpoint_id)"
}

upload_secure_files() {
  need_command curl
  need_command jq
  assert_apply_configuration
  [[ -n "${AZDO_SECURE_FILES_DIR:-}" ]] \
    || die "AZDO_SECURE_FILES_DIR must point to a local directory"
  [[ -d "$AZDO_SECURE_FILES_DIR" ]] \
    || die "Secure-file directory not found: $AZDO_SECURE_FILES_DIR"
  [[ -n "${AZURE_DEVOPS_EXT_PAT:-}" ]] \
    || die "AZURE_DEVOPS_EXT_PAT must be set in the current shell for secure-file upload"

  local project_id file_name local_path existing response_file status encoded_name
  project_id="$(resolve_project_id)"
  [[ "$project_id" =~ ^[0-9a-fA-F-]{36}$ ]] || die "Could not resolve an Azure DevOps project GUID"
  response_file="$(mktemp "$output_dir/secure-files-response.XXXXXX")"
  trap 'rm -f "$response_file"' RETURN

  while IFS= read -r file_name; do
    local_path="$AZDO_SECURE_FILES_DIR/$file_name"
    [[ -f "$local_path" ]] || die "Required secure file not found: $local_path"
    existing="$(curl --silent --show-error --fail \
      --user ":$AZURE_DEVOPS_EXT_PAT" \
      --get \
      --data-urlencode "name=$file_name" \
      "$AZDO_ORGANIZATION_URL/$project_id/_apis/distributedtask/securefiles?api-version=7.2-preview.1" \
      | jq -r --arg name "$file_name" '.value[]? | select(.name == $name) | .id' | head -n 1 || true)"
    if [[ -n "$existing" && "$existing" != "null" ]]; then
      echo "Secure file already exists; leaving it unchanged: $file_name"
      continue
    fi
    encoded_name="$(printf '%s' "$file_name" | jq -sRr @uri)"
    status="$(curl --silent --show-error --output "$response_file" --write-out '%{http_code}' \
      --user ":$AZURE_DEVOPS_EXT_PAT" \
      --header 'Content-Type: application/octet-stream' \
      --data-binary "@$local_path" \
      "$AZDO_ORGANIZATION_URL/$project_id/_apis/distributedtask/securefiles?name=$encoded_name&authorizePipelines=false&api-version=7.2-preview.1")"
    [[ "$status" == "200" || "$status" == "201" ]] \
      || die "Secure-file upload failed for $file_name (HTTP $status)"
    echo "Uploaded secure file without open pipeline authorization: $file_name"
  done <<'FILES'
aws-terraform-01-organization.backend.hcl
aws-terraform-01-organization.tfvars
aws-terraform-02-governance.backend.hcl
aws-terraform-02-governance.tfvars
aws-terraform-03-production.backend.hcl
aws-terraform-03-production.tfvars
FILES

  echo "Authorize the named pipeline on each uploaded secure file before running it."
}

preflight() {
  need_command aws
  need_command az
  assert_apply_configuration
  [[ -n "${AWS_PROFILE:-}" ]] || die "AWS_PROFILE must be set for preflight"

  local caller_account project_id
  caller_account="$(aws --profile "$AWS_PROFILE" --region "$AWS_REGION" sts get-caller-identity --query Account --output text)"
  [[ "$caller_account" == "$AWS_MANAGEMENT_ACCOUNT_ID" ]] \
    || die "AWS profile targets account $caller_account, expected $AWS_MANAGEMENT_ACCOUNT_ID"
  project_id="$(resolve_project_id)"
  [[ "$project_id" =~ ^[0-9a-fA-F-]{36}$ ]] || die "Could not resolve an Azure DevOps project GUID"
  az devops project show \
    --organization "$AZDO_ORGANIZATION_URL" \
    --project "$project_id" \
    --query '{id:id,name:name}' -o json
  echo "AWS management account verified: $caller_account"
  echo "Azure DevOps project verified: $project_id"
}

verify() {
  need_command jq
  write_manifests
  jq empty "$output_dir/aws-oidc-role-trust.json"
  jq empty "$output_dir/aws-oidc-provider-request.json"
  jq empty "$output_dir/aws-service-connection.json"
  if command -v terraform >/dev/null 2>&1; then
    terraform fmt -check -recursive "$repository_root"
  fi
  bash -n "$script_root/setup-pipeline.sh"
  echo "Local bootstrap artifacts and repository checks are valid."
}

case "$mode" in
  plan)
    write_manifests
    echo "Wrote read-only bootstrap artifacts to $output_dir"
    cat "$output_dir/replication-checklist.txt"
    ;;
  apply-aws)
    write_manifests
    apply_aws
    ;;
  apply-azure)
    write_manifests
    apply_azure
    ;;
  apply-all)
    write_manifests
    apply_aws
    apply_azure
    ;;
  upload-secure-files)
    write_manifests
    upload_secure_files
    ;;
  preflight)
    preflight
    ;;
  verify)
    verify
    ;;
esac
